require("dotenv").config();
const mongoose = require("mongoose");
const Product = require("./models/Product");

const realProducts = [
  // --- MEN'S WEAR ---
  {
    title: "Levi's Classic Denim Trucker Jacket",
    description: "Timeless denim trucker jacket featuring button-flap chest pockets and premium durable cotton denim in vintage indigo wash.",
    category: "men",
    brand: "levi",
    price: 120,
    salePrice: 89,
    totalStock: 25,
    averageReview: 4.8,
    image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Zara Slim-Fit Oxford Button-Down Shirt",
    description: "Crisp, tailored white cotton Oxford shirt with a structured button-down collar and sleek modern silhouette.",
    category: "men",
    brand: "zara",
    price: 65,
    salePrice: 48,
    totalStock: 35,
    averageReview: 4.6,
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Nike Dri-FIT Athletic Training T-Shirt",
    description: "Performance sportswear tee with sweat-wicking technology to keep you dry and comfortable all day.",
    category: "men",
    brand: "nike",
    price: 45,
    salePrice: 32,
    totalStock: 40,
    averageReview: 4.9,
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Adidas Originals Trefoil Fleece Hoodie",
    description: "Cozy fleece pullover hoodie with the classic Trefoil front logo and spacious kangaroo pocket.",
    category: "men",
    brand: "adidas",
    price: 75,
    salePrice: 58,
    totalStock: 18,
    averageReview: 4.7,
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Puma Classic Pique Polo Shirt",
    description: "Smart casual short-sleeve polo shirt cut from textured cotton pique with ribbed collar and Puma styling.",
    category: "men",
    brand: "puma",
    price: 50,
    salePrice: 35,
    totalStock: 8,
    averageReview: 4.5,
    image: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Nike Sportswear Club Fleece Crewneck",
    description: "Everyday fleece crewneck pullover with ribbed trims and embroidered Nike Futura logo.",
    category: "men",
    brand: "nike",
    price: 60,
    salePrice: 44,
    totalStock: 25,
    averageReview: 4.8,
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Zara Casual Linen Blend Long-Sleeve Shirt",
    description: "Lightweight, breathable linen-cotton blend shirt with relaxed camp collar in natural sand tone.",
    category: "men",
    brand: "zara",
    price: 70,
    salePrice: 52,
    totalStock: 19,
    averageReview: 4.7,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Levi's 511 Slim Fit Stretch Chino Pants",
    description: "Modern slim-cut chinos engineered with built-in stretch for maximum comfort and durability.",
    category: "men",
    brand: "levi",
    price: 80,
    salePrice: 59,
    totalStock: 22,
    averageReview: 4.9,
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Adidas Tiro 24 Athletic Track Jacket",
    description: "Signature 3-Stripes zip track jacket with ribbed stand-up collar and moisture-absorbing AEROREADY.",
    category: "men",
    brand: "adidas",
    price: 65,
    salePrice: 48,
    totalStock: 14,
    averageReview: 4.7,
    image: "https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=800&h=1000&q=80",
  },

  // --- WOMEN'S WEAR ---
  {
    title: "Zara Floral Bohemian Wrap Midi Dress",
    description: "Airy summer wrap dress featuring a botanical print, flattering V-neckline, and feminine ruffled hem.",
    category: "women",
    brand: "zara",
    price: 85,
    salePrice: 62,
    totalStock: 20,
    averageReview: 4.8,
    image: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "H&M Chunky Rib-Knit Cardigan",
    description: "Oversized warm-toned knit cardigan with dropped shoulders and tortoiseshell button closures.",
    category: "women",
    brand: "h&m",
    price: 55,
    salePrice: 39,
    totalStock: 28,
    averageReview: 4.6,
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Levi's High-Rise Straight Ankle Jeans",
    description: "Signature vintage-inspired denim with a high waist, straight leg cut, and subtle ankle distressing.",
    category: "women",
    brand: "levi",
    price: 98,
    salePrice: 74,
    totalStock: 15,
    averageReview: 4.9,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Nike Sportswear Essential Cropped Hoodie",
    description: "Comfortable fleece crop hoodie featuring minimal Nike swoosh embroidery and relaxed drop-shoulder cut.",
    category: "women",
    brand: "nike",
    price: 65,
    salePrice: 49,
    totalStock: 22,
    averageReview: 4.7,
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Zara Tailored Double-Breasted Blazer",
    description: "Sophisticated structured blazer with peak lapels, double-breasted buttoning, and interior pocket lining.",
    category: "women",
    brand: "zara",
    price: 110,
    salePrice: 82,
    totalStock: 6,
    averageReview: 4.9,
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "H&M High-Waisted Tailored Linen Trousers",
    description: "Breezy wide-leg linen trousers with pleat front detailing and comfortable waistband.",
    category: "women",
    brand: "h&m",
    price: 50,
    salePrice: 35,
    totalStock: 24,
    averageReview: 4.6,
    image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Nike Dri-FIT High-Waisted Workout Leggings",
    description: "Non-sheer athletic tights with a supportive high waistband and hidden drop-in storage pockets.",
    category: "women",
    brand: "nike",
    price: 70,
    salePrice: 52,
    totalStock: 30,
    averageReview: 4.9,
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Puma Classic Archive T7 Track Top",
    description: "Retro street track jacket with contrast 7cm sleeve panel inserts and metallic full-zip front.",
    category: "women",
    brand: "puma",
    price: 75,
    salePrice: 55,
    totalStock: 16,
    averageReview: 4.8,
    image: "https://images.unsplash.com/photo-1550614000-4895a10e1bfd?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Zara Satin Finish Midi Slip Skirt",
    description: "Silky satin bias-cut midi skirt with a concealed side zipper and fluid, shimmering drape.",
    category: "women",
    brand: "zara",
    price: 60,
    salePrice: 42,
    totalStock: 18,
    averageReview: 4.7,
    image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=800&h=1000&q=80",
  },

  // --- KIDS' WEAR ---
  {
    title: "H&M Cotton Colorblock Pullover Hoodie",
    description: "Soft brushed fleece hoodie with vibrant colorblock panels and comfortable ribbed cuffs for kids.",
    category: "kids",
    brand: "h&m",
    price: 35,
    salePrice: 25,
    totalStock: 30,
    averageReview: 4.8,
    image: "https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Nike Youth Sportswear Tracksuit Set",
    description: "Matching athletic tracksuit with zip jacket and cuffed joggers crafted from lightweight breathable knit.",
    category: "kids",
    brand: "nike",
    price: 75,
    salePrice: 55,
    totalStock: 18,
    averageReview: 4.9,
    image: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Adidas Kids Adicolor Graphic Tee",
    description: "Playful 100% soft organic cotton graphic tee designed for active all-day wear and everyday school style.",
    category: "kids",
    brand: "adidas",
    price: 28,
    salePrice: 20,
    totalStock: 35,
    averageReview: 4.7,
    image: "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Puma Youth Windbreaker Rain Jacket",
    description: "Water-resistant hooded windbreaker with reflective Puma accents and protective storm flap.",
    category: "kids",
    brand: "puma",
    price: 55,
    salePrice: 38,
    totalStock: 12,
    averageReview: 4.6,
    image: "https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Adidas Youth Trefoil Crew Sweatshirt",
    description: "Soft cotton-blend French terry sweatshirt featuring the classic oversized front Trefoil print.",
    category: "kids",
    brand: "adidas",
    price: 45,
    salePrice: 32,
    totalStock: 20,
    averageReview: 4.7,
    image: "https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Zara Kids Quilted Hooded Puffer Vest",
    description: "Lightweight thermal insulated vest with detachable hood and fleece-lined side pockets.",
    category: "kids",
    brand: "zara",
    price: 50,
    salePrice: 38,
    totalStock: 15,
    averageReview: 4.8,
    image: "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Levi's Kids Denim Overall Dungarees",
    description: "Durable vintage-wash denim overalls with adjustable metal clasps and multiple utility pockets.",
    category: "kids",
    brand: "levi",
    price: 55,
    salePrice: 40,
    totalStock: 18,
    averageReview: 4.9,
    image: "https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Puma Youth Essentials Graphic Logo Hoodie",
    description: "Everyday fleece hoodie with bold Puma Cat logo on chest and ribbed comfort cuffs.",
    category: "kids",
    brand: "puma",
    price: 40,
    salePrice: 28,
    totalStock: 26,
    averageReview: 4.6,
    image: "https://images.unsplash.com/photo-1503945438517-f65904a52ce6?auto=format&fit=crop&w=800&h=1000&q=80",
  },

  // --- FOOTWEAR ---
  {
    title: "Nike Air Max Retro Low-Top Sneakers",
    description: "Iconic streetwear sneaker with visible Air cushioning sole unit and premium multi-texture overlays.",
    category: "footwear",
    brand: "nike",
    price: 150,
    salePrice: 119,
    totalStock: 15,
    averageReview: 5.0,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Adidas Ultraboost Performance Running Shoes",
    description: "Energy-returning Boost cushioning midsole combined with a supportive Primeknit breathable upper.",
    category: "footwear",
    brand: "adidas",
    price: 180,
    salePrice: 139,
    totalStock: 12,
    averageReview: 4.9,
    image: "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Puma Suede Classic Heritage Sneakers",
    description: "Vintage basketball icon built with premium soft suede leather and the signature white Formstrip.",
    category: "footwear",
    brand: "puma",
    price: 85,
    salePrice: 64,
    totalStock: 22,
    averageReview: 4.7,
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Nike Air Force 1 '07 All-White",
    description: "Crisp all-white leather classic with encapsulated Nike Air cushioning and durable pivot-point sole.",
    category: "footwear",
    brand: "nike",
    price: 115,
    salePrice: 95,
    totalStock: 20,
    averageReview: 5.0,
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Adidas Stan Smith Timeless Tennis Shoes",
    description: "Clean minimalist leather sneaker with perforated 3-stripes and classic green heel tab.",
    category: "footwear",
    brand: "adidas",
    price: 100,
    salePrice: 79,
    totalStock: 16,
    averageReview: 4.8,
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Nike Pegasus 40 Road Running Shoes",
    description: "Springy, energized daily trainer with dual Zoom Air units and engineered breathable mesh upper.",
    category: "footwear",
    brand: "nike",
    price: 140,
    salePrice: 109,
    totalStock: 14,
    averageReview: 5.0,
    image: "https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Adidas NMD_R1 Urban Lifestyle Sneakers",
    description: "Modern street runner with responsive cushioning and a flexible, breathable silhouette.",
    category: "footwear",
    brand: "adidas",
    price: 160,
    salePrice: 125,
    totalStock: 12,
    averageReview: 4.8,
    image: "https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Puma RS-X Bold Colorway Sneakers",
    description: "Chunky retro silhouette featuring extreme design details, mixed leather mesh, and bold accents.",
    category: "footwear",
    brand: "puma",
    price: 110,
    salePrice: 82,
    totalStock: 15,
    averageReview: 4.7,
    image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Zara Classic Leather Chelsea Boots",
    description: "Sleek round-toe Chelsea boots crafted with genuine polished leather and elastic side gores.",
    category: "footwear",
    brand: "zara",
    price: 130,
    salePrice: 99,
    totalStock: 10,
    averageReview: 4.9,
    image: "https://images.unsplash.com/photo-1575537302964-96cd47c06b1b?auto=format&fit=crop&w=800&h=1000&q=80",
  },

  // --- ACCESSORIES ---
  {
    title: "Zara Minimalist Vegan Leather Crossbody Bag",
    description: "Structured everyday handbag with gold hardware accents, magnetic flap closure, and detachable strap.",
    category: "accessories",
    brand: "zara",
    price: 65,
    salePrice: 48,
    totalStock: 16,
    averageReview: 4.7,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Puma Minimalist Analog Quartz Watch",
    description: "Clean stainless steel watch with matte dial, mineral glass crystal, and genuine leather wristband.",
    category: "accessories",
    brand: "puma",
    price: 110,
    salePrice: 85,
    totalStock: 14,
    averageReview: 4.8,
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Adidas Originals Trefoil Curved Snapback Cap",
    description: "Classic six-panel curved brim cap featuring high-density embroidery and adjustable rear strap.",
    category: "accessories",
    brand: "adidas",
    price: 28,
    salePrice: 20,
    totalStock: 45,
    averageReview: 4.6,
    image: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Levi's Genuine Leather Reversible Belt",
    description: "Heavy-duty full-grain leather belt with a rotating metallic buckle that switches between black and brown.",
    category: "accessories",
    brand: "levi",
    price: 45,
    salePrice: 32,
    totalStock: 24,
    averageReview: 4.8,
    image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "H&M Tortoiseshell Retro Sunglasses",
    description: "Vintage round-frame sunglasses featuring UV400 protective polarized lenses and tortoiseshell acetate.",
    category: "accessories",
    brand: "h&m",
    price: 30,
    salePrice: 22,
    totalStock: 30,
    averageReview: 4.5,
    image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Zara Structured Leather Shoulder Bag",
    description: "Sophisticated shoulder bag with chain-link hardware, magnetic closure, and inner zip divider.",
    category: "accessories",
    brand: "zara",
    price: 70,
    salePrice: 50,
    totalStock: 15,
    averageReview: 4.8,
    image: "https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "H&M Canvas Everyday Weekend Duffle Bag",
    description: "Heavy-duty washed canvas duffle with reinforced faux-leather handles and detachable strap.",
    category: "accessories",
    brand: "h&m",
    price: 50,
    salePrice: 35,
    totalStock: 22,
    averageReview: 4.6,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Levi's Classic Aviator Metal Sunglasses",
    description: "Timeless teardrop aviator frame in polished gunmetal with 100% UV-protective tinted lenses.",
    category: "accessories",
    brand: "levi",
    price: 55,
    salePrice: 38,
    totalStock: 28,
    averageReview: 4.7,
    image: "https://images.unsplash.com/photo-1533827432537-70133748f5c8?auto=format&fit=crop&w=800&h=1000&q=80",
  },
  {
    title: "Nike Heritage Classic Everyday Backpack",
    description: "Durable polyester backpack with a roomy dual-zip main compartment and internal laptop sleeve.",
    category: "accessories",
    brand: "nike",
    price: 40,
    salePrice: 29,
    totalStock: 35,
    averageReview: 4.9,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&h=1000&q=80",
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URL);
    console.log("Connected to MongoDB Atlas successfully!");

    let addedCount = 0;
    let updatedCount = 0;

    for (const prod of realProducts) {
      const existing = await Product.findOne({ title: prod.title });
      if (!existing) {
        await Product.create(prod);
        addedCount++;
        console.log(`+ Added: ${prod.title} (${prod.category} - ${prod.brand})`);
      } else {
        // Update image or details if needed (e.g. fixing broken image URLs)
        if (existing.image !== prod.image) {
          existing.image = prod.image;
          await existing.save();
          updatedCount++;
          console.log(`~ Updated image for: ${prod.title}`);
        } else {
          console.log(`= Already exists: ${prod.title}`);
        }
      }
    }

    const total = await Product.countDocuments();
    console.log(`\nDone! Added ${addedCount} new products, updated ${updatedCount}. Total products in database: ${total}`);
    await mongoose.disconnect();
  } catch (error) {
    console.error("Seeding error:", error);
    process.exit(1);
  }
}

seed();
